name: Flutter Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get the branch name
        run: echo "Current branch name is ${{ github.ref_name }}"
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Install Flutter Dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release --base-href "/bouncy_ball_physics/" --web-renderer canvaskit

      - name: setup chrome
        uses: nanasess/setup-chromedriver@v2

      - name: ğŸª› Start Chromedriver
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub --port=4444 --verbose &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

      - name: ğŸ“¢ Check Chromedriver Version
        run: chromedriver -v

      - name: â³ Delay
        run: |
          echo "Waiting for Chromedriver to start..."
          sleep 15

      - name: ğŸš€ Run Integration Test
        run: |
          flutter drive --verbose-system-logs -d web-server --driver=test_driver/integration_test.dart --target=integration_test/test.dart

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Chore: update screenshot"
          file_pattern: "**/*.png"
          repository: .
          skip_fetch: false
